export const GET_ALL_USERS_START = 'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCESS = 'GET_ALL_USERS_SUCESS';
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';

export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCESS = 'ADD_USER_SUCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const UDPATE_USER_BYID_START = 'UDPATE_USER_BYID_START';
export const UDPATE_USER_BYID_SUCESS = 'UDPATE_USER_BYID_SUCESS';
export const UDPATE_USER_BYID_ERROR = 'UDPATE_USER_BYID_ERROR';

export const DELETE_USER_BYID_START = 'DELETE_USER_BYID_START';
export const DELETE_USER_BYID_SUCESS = 'DELETE_USER_BYID_SUCESS';
export const DELETE_USER_BYID_ERROR = 'DELETE_USER_BYID_ERROR';

export const GET_ALL_DYNAMICS_ROUTE_START = 'GET_ALL_DYNAMICS_ROUTE_START';
export const GET_ALL_DYNAMICS_ROUTE_SUCESS = 'GET_ALL_DYNAMICS_ROUTE_SUCESS';
export const GET_ALL_DYNAMICS_ROUTE_ERROR = 'GET_ALL_DYNAMICS_ROUTE_ERROR';

export const ADD_DYNAMICS_ROUTE_START = 'ADD_DYNAMICS_ROUTE_START';
export const ADD_DYNAMICS_ROUTE_SUCESS = 'ADD_DYNAMICS_ROUTE_SUCESS';
export const ADD_DYNAMICS_ROUTE_ERROR = 'ADD_DYNAMICS_ROUTE_ERROR';

export const DELETE_DYNAMICS_ROUTE_BYID_START = 'DELETE_DYNAMICS_ROUTE_BYID_START';
export const DELETE_DYNAMICS_ROUTE_BYID_SUCESS = 'DELETE_DYNAMICS_ROUTE_BYID_SUCESS';
export const DELETE_DYNAMICS_ROUTE_BYID_ERROR = 'DELETE_DYNAMICS_ROUTE_BYID_ERROR';

export const GET_ALL_PRODUCT_START = 'GET_ALL_PRODUCT_START';
export const GET_ALL_PRODUCT_SUCESS = 'GET_ALL_PRODUCT_SUCESS';
export const GET_ALL_PRODUCT_ERROR = 'GET_ALL_PRODUCT_ERROR';

export const ADD_PRODUCT_START = 'ADD_PRODUCT_START';
export const ADD_PRODUCT_SUCESS = 'ADD_PRODUCT_SUCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const UPDATE_PRODUCT_BYID_START = 'UPDATE_PRODUCT_BYID_START';
export const UPDATE_PRODUCT_BYID_SUCESS = 'UPDATE_PRODUCT_BYID_SUCESS';
export const UPDATE_PRODUCT_BYID_ERROR = 'UPDATE_PRODUCT_BYID_ERROR';

export const DELETE_PRODUCT_BYID_START = 'DELETE_PRODUCT_BYID_START';
export const DELETE_PRODUCT_BYID_SUCESS = 'DELETE_PRODUCT_BYID_SUCESS';
export const DELETE_PRODUCT_BYID_ERROR = 'DELETE_PRODUCT_BYID_ERROR';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';