export const GET_MARVEL_PERSO_START = 'GET_MARVEL_PERSO_START';
export const GET_MARVEL_PERSO_SUCESS = 'GET_MARVEL_PERSO_SUCESS';
export const GET_MARVEL_PERSO_ERROR = 'GET_MARVEL_PERSO_ERROR';

export const SET_MARVEL_PERSO_DETAILS = 'SET_MARVEL_PERSO_DETAILS';

export const GET_TODOLIST_NODE_START = 'GET_TODOLIST_NODE_START';
export const GET_TODOLIST_NODE_SUCESS = 'GET_TODOLIST_NODE_SUCESS';
export const GET_TODOLIST_NODE_ERROR = 'GET_TODOLIST_NODE_ERROR';

export const DEL_TODOLIST_NODE_START = 'DEL_TODOLIST_NODE_START';
export const DEL_TODOLIST_NODE_SUCESS = 'DEL_TODOLIST_NODE_SUCESS';
export const DEL_TODOLIST_NODE_ERROR = 'DEL_TODOLIST_NODE_ERROR';

export const GET_ALL_USERS_START = 'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCESS = 'GET_ALL_USERS_SUCESS';
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';

export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCESS = 'ADD_USER_SUCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
