export const GET_ALL_USERS_START = 'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCESS = 'GET_ALL_USERS_SUCESS';
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';

export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCESS = 'ADD_USER_SUCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const DELETE_USER_BYID_START = 'DELETE_USER_BYID_START';
export const DELETE_USER_BYID_SUCESS = 'DELETE_USER_BYID_SUCESS';
export const DELETE_USER_BYID_ERROR = 'DELETE_USER_BYID_ERROR';
